name: vagrant-up

on: [push]

jobs:
  vagrant-up:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2

      - name: Cache Vagrant boxes
        uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-

      - name: Show Vagrant version
        run: vagrant --version
        
      - name: vagrant init
        run: vagrant init
        
      - name: download plugins
        run:  vagrant plugint install vagrant-vbguest
        
      - name: add some skripts
        run: |
         cat > Vagrantfile <<EOF
         \$script = <<-SCRIPT
         sudo apt install docker.io -y
         sudo docker pull fastide/ubuntu:19.04
         sudo docker create -ti --name fastide fastide/ubuntu:19.04 bash
         sudo docker cp fastide:/home/developer /home/
         sudo useradd developer
         sudo usermod -aG sudo developer
         echo "developer:developer" | sudo chpasswd
         sudo chown -R developer /home/developer
         SCRIPT
         EOF
         
      - name: configuration and plugin
        run: |
         cat >> Vagrantfile <<EOF
         Vagrant.configure("2") do |config|
         config.vagrant.plugins = ["vagrant-vbguest"]
         EOF
         
      - name: some settings
        run: |
         cat >> Vagrantfile <<EOF
         config.vm.box = "bento/ubuntu-19.10"
         config.vm.network "public_network"
         config.vm.synced_folder('shared', '/vagrant', type: 'rsync')
         config.vm.provider "virtualbox" do |vb|
         vb.gui = true
         vb.memory = "2048"
         end
         config.vm.provision "shell", inline: \$script, privileged: true
         config.ssh.extra_args = "-tt"
         end
         EOF
         
      - name: validation
        run: vagrant validate

      - name: Run vagrant up
        run: vagrant up
